name: Build
on: [push]

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - name: Build project
        run: |
          make archive
      
      - uses: actions/upload-artifact@v4
        with:
          name: taragen-dist
          path: dist/