name: Build
on: [push]
jobs:
  build:
    name: Build
    uses: progrium/github-workflows/.github/workflows/golang-cli-build.yml@main
    with:
      bin-name: taragen
      go-version: '1.23.1'
    secrets: inherit